<<: !include esp32-ble-example-multiple-devices.yaml

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 1s
    enable_fake_traffic: true
  - id: bms1
    ble_client_id: client1
    update_interval: 1s
    enable_fake_traffic: true
